### PR TITLE
Added stubs for PRJ type problems

### LINKED ISSUE #6: Add stubs for project based problems

### PR DESCRIPTION
**Pull request by faza**
- python2
- python3
- java7
- java8

Fixes #6

Signed-off-by: Faza Mahamood <faza@doselect.com>

### CODE REVIEW

**Comment by dolftax** [comment]
Add atleast two files per technology?

**Comment by faza** [comment]
@dolftax Candidate might get confused if we add one more source file. What do you suggest to add?

**Comment by dolftax** [comment]
This is supposed to be PRJ based, right?

**Comment by faza** [comment]
Yeah

**Comment by faza** [comment]
@dolftax Done

**Pull request merged**
